import { describe, it, expect } from 'vitest';
import { compileYamlToQuestionnaire } from './yaml-to-questionnaire.js';

// Uses the real bundled data/form-schematics.schema.json + data/graphs.bundle.json (generated by
// `npm run build:kernel`) rather than mocking them — Patient.gender and Observation.valueQuantity
// are real paths confirmed present in the current graph bundle, so these exercise the actual
// validation rules a form author would hit, not a fabricated approximation of them.

const VALID_YAML = `
formId: test-vitals-v1
title: "Test Vitals"
composition:
  - resourceType: Patient
    fields:
      - id: "gender"
        path: "Patient.gender"
        label: "Sex"
        uiComponent: "TextInput"
  - resourceType: Observation
    fields:
      - id: "systolic"
        path: "Observation.valueQuantity"
        label: "Systolic BP"
        uiComponent: "NumericInput"
        unit: "mmHg"
`;

describe('compileYamlToQuestionnaire', () => {
    it('compiles valid YAML into a FHIR Questionnaire', () => {
        const result = compileYamlToQuestionnaire(VALID_YAML);
        expect(result.success).toBe(true);
        expect(result.questionnaire.resourceType).toBe('Questionnaire');
        expect(result.questionnaire.id).toBe('test-vitals-v1');
        expect(result.questionnaire.item).toHaveLength(2);

        const [patientGroup, obsGroup] = result.questionnaire.item;
        expect(patientGroup.item[0]).toMatchObject({ linkId: 'gender', text: 'Sex', type: 'string' });
        expect(obsGroup.item[0]).toMatchObject({ linkId: 'systolic', type: 'decimal', repeats: false });
    });

    it('maps uiComponent to the correct FHIR item type', () => {
        const yamlSource = `
formId: test-types-v1
composition:
  - resourceType: Observation
    fields:
      - id: "a"
        path: "Observation.valueQuantity"
        label: "A"
        uiComponent: "NumericInput"
      - id: "b"
        path: "Observation.valueQuantity.comparator"
        label: "B"
        uiComponent: "Dropdown"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(true);
        const [a, b] = result.questionnaire.item[0].item;
        expect(a.type).toBe('decimal');
        expect(b.type).toBe('choice');
    });

    // Optional journey: tag (Patient/Front Desk vs Hospital-management workflows surfacing a
    // custom form themselves) — see clinux-custom-forms-in-patient-hospital-journeys memory
    // note. A plain top-level pass-through, same non-standard-but-established convention this
    // compiler already uses for id/title.
    it('passes an optional journey tag through onto the compiled Questionnaire', () => {
        const result = compileYamlToQuestionnaire(VALID_YAML.replace('title: "Test Vitals"', 'title: "Test Vitals"\njourney: patient'));
        expect(result.success).toBe(true);
        expect(result.questionnaire.journey).toBe('patient');
    });

    it('omits journey entirely from the compiled Questionnaire when not set in the YAML', () => {
        const result = compileYamlToQuestionnaire(VALID_YAML);
        expect(result.success).toBe(true);
        expect(result.questionnaire.journey).toBeUndefined();
    });

    it('rejects an unrecognized journey value', () => {
        const result = compileYamlToQuestionnaire(VALID_YAML.replace('title: "Test Vitals"', 'title: "Test Vitals"\njourney: not-a-real-journey'));
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Structural Error'))).toBe(true);
    });

    it('rejects malformed YAML with a syntax error', () => {
        const result = compileYamlToQuestionnaire('formId: [unclosed');
        expect(result.success).toBe(false);
        expect(result.errors[0]).toMatch(/YAML Syntax Error/);
    });

    it('rejects YAML missing required top-level fields', () => {
        const result = compileYamlToQuestionnaire('title: "No formId or composition"');
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Structural Error'))).toBe(true);
    });

    it('rejects a field path that does not exist in the resource graph shard', () => {
        const yamlSource = `
formId: test-bad-path-v1
composition:
  - resourceType: Patient
    fields:
      - id: "x"
        path: "Patient.thisFieldDoesNotExist"
        label: "X"
        uiComponent: "TextInput"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Invalid FHIR Path'))).toBe(true);
    });

    it('rejects a resourceType not present in the graph bundle at all', () => {
        const yamlSource = `
formId: test-bad-resource-v1
composition:
  - resourceType: NotARealFhirResource
    fields:
      - id: "x"
        path: "NotARealFhirResource.foo"
        label: "X"
        uiComponent: "TextInput"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Composition Mismatch'))).toBe(true);
    });

    // Mirrors the real merged tools/system-forms/system-encounter-composition-v1.yaml shape:
    // 5 composition blocks, Encounter first (subjectType is derived only from composition[0]'s
    // resourceType), with Vitals/Prescription marked repeats: true for multiple readings/meds
    // per visit while SOAP/Billing stay singular.
    it('compiles a 5-block Encounter-composition form with subjectType and repeats set correctly', () => {
        const yamlSource = `
formId: test-encounter-composition-v1
title: "Consultation"
composition:
  - resourceType: Encounter
    id: section_encounter
    fields:
      - id: "encounter_status"
        path: "Encounter.status"
        label: "Status"
        uiComponent: "Dropdown"
        choices: ["arrived", "finished"]
  - resourceType: Observation
    id: section_vitals
    repeats: true
    fields:
      - id: "vitals_systolic"
        path: "Observation.valueQuantity"
        label: "Systolic BP"
        uiComponent: "NumericInput"
  - resourceType: Condition
    id: section_soap
    fields:
      - id: "soap_subjective"
        path: "Condition.note.text"
        label: "Subjective"
        uiComponent: "TextInput"
  - resourceType: MedicationRequest
    id: section_prescription
    repeats: true
    fields:
      - id: "rx_status"
        path: "MedicationRequest.status"
        label: "Status"
        uiComponent: "Dropdown"
        choices: ["active", "completed"]
  - resourceType: Invoice
    id: section_billing
    fields:
      - id: "billing_status"
        path: "Invoice.status"
        label: "Status"
        uiComponent: "Dropdown"
        choices: ["draft", "issued"]
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(true);
        expect(result.questionnaire.subjectType).toEqual(['Encounter']);
        expect(result.questionnaire.item).toHaveLength(5);

        const byLinkId = Object.fromEntries(result.questionnaire.item.map((g) => [g.linkId, g]));
        expect(byLinkId.section_vitals.repeats).toBe(true);
        expect(byLinkId.section_prescription.repeats).toBe(true);
        expect(byLinkId.section_encounter.repeats).toBe(false);
        expect(byLinkId.section_soap.repeats).toBe(false);
        expect(byLinkId.section_billing.repeats).toBe(false);
    });

    it('carries choices through to answerOption for a Dropdown field', () => {
        const yamlSource = `
formId: test-choices-v1
composition:
  - resourceType: Observation
    fields:
      - id: "cmp"
        path: "Observation.valueQuantity.comparator"
        label: "Comparator"
        uiComponent: "Dropdown"
        choices: ["<", ">", "="]
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(true);
        expect(result.questionnaire.item[0].item[0].answerOption).toEqual([
            { valueString: '<' }, { valueString: '>' }, { valueString: '=' },
        ]);
    });
});
