import { describe, it, expect } from 'vitest';
import { compileYamlToQuestionnaire } from './yaml-to-questionnaire.js';

// Uses the real bundled data/form-schematics.schema.json + data/graphs.bundle.json (generated by
// `npm run build:kernel`) rather than mocking them — Patient.gender and Observation.valueQuantity
// are real paths confirmed present in the current graph bundle, so these exercise the actual
// validation rules a form author would hit, not a fabricated approximation of them.

const VALID_YAML = `
formId: test-vitals-v1
title: "Test Vitals"
composition:
  - resourceType: Patient
    fields:
      - id: "gender"
        path: "Patient.gender"
        label: "Sex"
        uiComponent: "TextInput"
  - resourceType: Observation
    fields:
      - id: "systolic"
        path: "Observation.valueQuantity"
        label: "Systolic BP"
        uiComponent: "NumericInput"
        unit: "mmHg"
`;

describe('compileYamlToQuestionnaire', () => {
    it('compiles valid YAML into a FHIR Questionnaire', () => {
        const result = compileYamlToQuestionnaire(VALID_YAML);
        expect(result.success).toBe(true);
        expect(result.questionnaire.resourceType).toBe('Questionnaire');
        expect(result.questionnaire.id).toBe('test-vitals-v1');
        expect(result.questionnaire.item).toHaveLength(2);

        const [patientGroup, obsGroup] = result.questionnaire.item;
        expect(patientGroup.item[0]).toMatchObject({ linkId: 'gender', text: 'Sex', type: 'string' });
        expect(obsGroup.item[0]).toMatchObject({ linkId: 'systolic', type: 'decimal', repeats: false });
    });

    it('maps uiComponent to the correct FHIR item type', () => {
        const yamlSource = `
formId: test-types-v1
composition:
  - resourceType: Observation
    fields:
      - id: "a"
        path: "Observation.valueQuantity"
        label: "A"
        uiComponent: "NumericInput"
      - id: "b"
        path: "Observation.valueQuantity.comparator"
        label: "B"
        uiComponent: "Dropdown"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(true);
        const [a, b] = result.questionnaire.item[0].item;
        expect(a.type).toBe('decimal');
        expect(b.type).toBe('choice');
    });

    it('rejects malformed YAML with a syntax error', () => {
        const result = compileYamlToQuestionnaire('formId: [unclosed');
        expect(result.success).toBe(false);
        expect(result.errors[0]).toMatch(/YAML Syntax Error/);
    });

    it('rejects YAML missing required top-level fields', () => {
        const result = compileYamlToQuestionnaire('title: "No formId or composition"');
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Structural Error'))).toBe(true);
    });

    it('rejects a field path that does not exist in the resource graph shard', () => {
        const yamlSource = `
formId: test-bad-path-v1
composition:
  - resourceType: Patient
    fields:
      - id: "x"
        path: "Patient.thisFieldDoesNotExist"
        label: "X"
        uiComponent: "TextInput"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Invalid FHIR Path'))).toBe(true);
    });

    it('rejects a resourceType not present in the graph bundle at all', () => {
        const yamlSource = `
formId: test-bad-resource-v1
composition:
  - resourceType: NotARealFhirResource
    fields:
      - id: "x"
        path: "NotARealFhirResource.foo"
        label: "X"
        uiComponent: "TextInput"
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(false);
        expect(result.errors.some((e) => e.includes('Composition Mismatch'))).toBe(true);
    });

    it('carries choices through to answerOption for a Dropdown field', () => {
        const yamlSource = `
formId: test-choices-v1
composition:
  - resourceType: Observation
    fields:
      - id: "cmp"
        path: "Observation.valueQuantity.comparator"
        label: "Comparator"
        uiComponent: "Dropdown"
        choices: ["<", ">", "="]
`;
        const result = compileYamlToQuestionnaire(yamlSource);
        expect(result.success).toBe(true);
        expect(result.questionnaire.item[0].item[0].answerOption).toEqual([
            { valueString: '<' }, { valueString: '>' }, { valueString: '=' },
        ]);
    });
});
