// Copied from clinuxflow-fhir-api (scripts/lib/dictionary.js) — clinuxflow-api builds its FHIR path dictionary
// from the same pinned official packages (fhir-packages.json) instead of @smile-cdr/fhirts.
// Keep in step with fhir-api: change it there first, then copy.
// FHIR path dictionary: every element path a form author may bind a field to, per resource,
// with its type, cardinality and binding. Built from the official R4 core snapshots, expanding
// complex datatypes a few levels deep (Organization.address.line, Patient.telecom.system, ...).
//
// It replaces clinuxflow-api's dictionary, which was generated by walking the
// @smile-cdr/fhirts TypeScript classes. Same purpose; the source is now HL7's own definitions.

/** The resources clinuxflow-api's compiler allowed (tools/clinixflow.config.json), plus
 * everything ABDM or ClinuxFlow profiles (added by the build). */
export const DICTIONARY_RESOURCES = [
    'Patient', 'Observation', 'Encounter', 'Condition', 'MedicationRequest', 'Organization', 'Location',
    'Practitioner', 'PractitionerRole', 'Coverage', 'Claim', 'Invoice', 'Account', 'DiagnosticReport',
    'ServiceRequest', 'Specimen', 'Appointment', 'Schedule', 'Slot', 'Medication', 'MedicationDispense',
    'SupplyDelivery', 'PaymentNotice', 'Device', 'DeviceMetric', 'Consent', 'Contract', 'HealthcareService',
    'EpisodeOfCare', 'PlanDefinition', 'OrganizationAffiliation', 'Task', 'Questionnaire', 'QuestionnaireResponse',
];

// Datatypes not expanded: their insides are never form fields (or are recursive).
const OPAQUE = new Set(['Extension', 'Narrative', 'Meta', 'Resource', 'Reference', 'Element', 'BackboneElement', 'xhtml']);
const SKIP_CHILDREN = new Set(['id', 'extension', 'modifierExtension']);
const MAX_DATATYPE_DEPTH = 3;

const isPrimitive = (code) => /^[a-z]/.test(code);
const upperFirst = (x) => x.charAt(0).toUpperCase() + x.slice(1);

/** A choice element ("value[x]") is bound by forms under its concrete names ("valueQuantity"):
 * returns [path, typeCode] for the element itself or one per allowed type. */
function concreteNames(path, el) {
    if (!path.endsWith('[x]')) return [[path, null]];
    const stem = path.slice(0, -3);
    return (el.types || []).map((t) => [stem + upperFirst(t.code), t.code]);
}

function children(sd, parentId) {
    return sd.elements.filter((e) => !e.sliceName && e.id.startsWith(parentId + '.') && !e.id.slice(parentId.length + 1).includes('.'));
}

function entry(el) {
    const e = { types: (el.types || []).map((t) => t.code), min: el.min, max: el.max };
    if (el.binding) e.binding = el.binding;
    if (el.contentReference) e.contentReference = el.contentReference;
    return e;
}

/**
 * @param {string[]} resources
 * @param {(type: string) => object|undefined} typeSd compact core SD by type name
 * @returns {Record<string, Record<string, object>>}
 */
export function buildDictionary(resources, typeSd) {
    const out = {};
    for (const resource of resources) {
        const sd = typeSd(resource);
        if (!sd) continue;
        const paths = {};
        const walkDatatype = (prefix, type, depth) => {
            const tsd = typeSd(type);
            if (!tsd || depth > MAX_DATATYPE_DEPTH) return;
            for (const el of children(tsd, type)) {
                const name = el.id.slice(type.length + 1);
                if (SKIP_CHILDREN.has(name)) continue;
                const path = `${prefix}.${name}`;
                paths[path] = entry(el);
                for (const [concrete, only] of concreteNames(path, el)) {
                    if (only) paths[concrete] = { ...entry(el), types: [only] };
                    for (const t of el.types || []) {
                        if (only && t.code !== only) continue;
                        if (!isPrimitive(t.code) && !OPAQUE.has(t.code)) walkDatatype(concrete, t.code, depth + 1);
                    }
                }
            }
        };
        const walkResource = (id) => {
            for (const el of children(sd, id)) {
                // Extensions on the resource and on backbone elements are real form targets
                // (e.g. Practitioner.qualification.extension); element ids are not.
                if (el.id.slice(id.length + 1) === 'id' && id !== resource) continue;
                paths[el.id] = entry(el);
                const types = el.types || [];
                if (types.some((t) => t.code === 'BackboneElement')) walkResource(el.id);
                for (const [concrete, only] of concreteNames(el.id, el)) {
                    if (only) paths[concrete] = { ...entry(el), types: [only] };
                    for (const t of types) {
                        if (only && t.code !== only) continue;
                        if (!isPrimitive(t.code) && !OPAQUE.has(t.code)) walkDatatype(concrete, t.code, 1);
                    }
                }
            }
        };
        walkResource(resource);
        out[resource] = paths;
    }
    return out;
}
